### PR TITLE
Beginning of Bug Report

### PR DESCRIPTION
**Pull request by ThePlayerZero**
This code is the beginning of the In-game Bug Reporting system!

### CODE REVIEW

**Comment by DarthNihilus1** [comment]
You can merge branches without prs btw just do git merge branch or do it from desktop

**Comment by ThePlayerZero** [comment]
> You can merge branches without prs btw just do git merge branch or do it from desktop

What does prs mean?

**Comment by DarthNihilus1** [comment]
Pull requests

**Comment by ThePlayerZero** [comment]
Ah. If I make a Pull Request, it's probably by mistake.

**Pull request merged**
